{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import os\n",
    "\n",
    "risk_free_path = os.path.join('data', \"F-F_Research_Data_Factors_daily.CSV\")\n",
    "rf_df = pd.read_csv(risk_free_path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "rf_df['date'] = pd.to_datetime(rf_df['date'], format=\"%Y%m%d\").dt.date"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "rf_df = rf_df.drop(rf_df.columns[1:4], axis=1)\n",
    "rf_df.columns = [\"date\", \"risk_free_return\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "rf_df.to_csv(\"data/risk_free_us.csv\", index=0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\piotr\\Workspaces\\estimating-beta\\experiment.py:142: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  data.loc[:, 'beta'] = eval_beta(data, beta_corr_window)\n",
      "59it [00:01, 50.83it/s]\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "\nAll the 59 fits failed.\nIt is very likely that your model is misconfigured.\nYou can try to debug the error by setting error_score='raise'.\n\nBelow are more details about the failures:\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\piotr\\AppData\\Local\\Temp\\ipykernel_7892\\2658662950.py\", line 33, in fit\n    return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\esn.py\", line 21, in fit\n    self.readout.fit(mapped_input, target, washout=self.washout)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\readout\\nn_readout.py\", line 60, in fit\n    y_pred = self.model(X)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 217, in forward\n    input = module(input)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    return F.linear(input, self.weight, self.bias)\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (5x42 and 21x4)\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\piotr\\AppData\\Local\\Temp\\ipykernel_7892\\2658662950.py\", line 33, in fit\n    return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\esn.py\", line 21, in fit\n    self.readout.fit(mapped_input, target, washout=self.washout)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\readout\\nn_readout.py\", line 60, in fit\n    y_pred = self.model(X)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 217, in forward\n    input = module(input)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    return F.linear(input, self.weight, self.bias)\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (10x42 and 21x4)\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\piotr\\AppData\\Local\\Temp\\ipykernel_7892\\2658662950.py\", line 33, in fit\n    return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\esn.py\", line 21, in fit\n    self.readout.fit(mapped_input, target, washout=self.washout)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\readout\\nn_readout.py\", line 60, in fit\n    y_pred = self.model(X)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 217, in forward\n    input = module(input)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    return F.linear(input, self.weight, self.bias)\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (15x42 and 21x4)\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\piotr\\AppData\\Local\\Temp\\ipykernel_7892\\2658662950.py\", line 33, in fit\n    return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\esn.py\", line 21, in fit\n    self.readout.fit(mapped_input, target, washout=self.washout)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\readout\\nn_readout.py\", line 60, in fit\n    y_pred = self.model(X)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 217, in forward\n    input = module(input)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    return F.linear(input, self.weight, self.bias)\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (20x42 and 21x4)\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\piotr\\AppData\\Local\\Temp\\ipykernel_7892\\2658662950.py\", line 33, in fit\n    return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\esn.py\", line 21, in fit\n    self.readout.fit(mapped_input, target, washout=self.washout)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\readout\\nn_readout.py\", line 60, in fit\n    y_pred = self.model(X)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 217, in forward\n    input = module(input)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    return F.linear(input, self.weight, self.bias)\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (25x42 and 21x4)\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\piotr\\AppData\\Local\\Temp\\ipykernel_7892\\2658662950.py\", line 33, in fit\n    return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\esn.py\", line 21, in fit\n    self.readout.fit(mapped_input, target, washout=self.washout)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\readout\\nn_readout.py\", line 60, in fit\n    y_pred = self.model(X)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 217, in forward\n    input = module(input)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    return F.linear(input, self.weight, self.bias)\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (30x42 and 21x4)\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\piotr\\AppData\\Local\\Temp\\ipykernel_7892\\2658662950.py\", line 33, in fit\n    return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\esn.py\", line 21, in fit\n    self.readout.fit(mapped_input, target, washout=self.washout)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\readout\\nn_readout.py\", line 60, in fit\n    y_pred = self.model(X)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 217, in forward\n    input = module(input)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    return F.linear(input, self.weight, self.bias)\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (35x42 and 21x4)\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\piotr\\AppData\\Local\\Temp\\ipykernel_7892\\2658662950.py\", line 33, in fit\n    return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\esn.py\", line 21, in fit\n    self.readout.fit(mapped_input, target, washout=self.washout)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\readout\\nn_readout.py\", line 60, in fit\n    y_pred = self.model(X)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 217, in forward\n    input = module(input)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    return F.linear(input, self.weight, self.bias)\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (40x42 and 21x4)\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\piotr\\AppData\\Local\\Temp\\ipykernel_7892\\2658662950.py\", line 33, in fit\n    return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\esn.py\", line 21, in fit\n    self.readout.fit(mapped_input, target, washout=self.washout)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\readout\\nn_readout.py\", line 60, in fit\n    y_pred = self.model(X)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 217, in forward\n    input = module(input)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    return F.linear(input, self.weight, self.bias)\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (45x42 and 21x4)\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\piotr\\AppData\\Local\\Temp\\ipykernel_7892\\2658662950.py\", line 33, in fit\n    return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\esn.py\", line 21, in fit\n    self.readout.fit(mapped_input, target, washout=self.washout)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\readout\\nn_readout.py\", line 60, in fit\n    y_pred = self.model(X)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 217, in forward\n    input = module(input)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    return F.linear(input, self.weight, self.bias)\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (50x42 and 21x4)\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\piotr\\AppData\\Local\\Temp\\ipykernel_7892\\2658662950.py\", line 33, in fit\n    return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\esn.py\", line 21, in fit\n    self.readout.fit(mapped_input, target, washout=self.washout)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\readout\\nn_readout.py\", line 60, in fit\n    y_pred = self.model(X)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 217, in forward\n    input = module(input)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    return F.linear(input, self.weight, self.bias)\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (55x42 and 21x4)\n\n--------------------------------------------------------------------------------\n48 fits failed with the following error:\nTraceback (most recent call last):\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\piotr\\AppData\\Local\\Temp\\ipykernel_7892\\2658662950.py\", line 33, in fit\n    return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\esn.py\", line 21, in fit\n    self.readout.fit(mapped_input, target, washout=self.washout)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\readout\\nn_readout.py\", line 60, in fit\n    y_pred = self.model(X)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 217, in forward\n    input = module(input)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    return F.linear(input, self.weight, self.bias)\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (60x42 and 21x4)\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[12], line 85\u001b[0m\n\u001b[0;32m     70\u001b[0m grid \u001b[39m=\u001b[39m {\n\u001b[0;32m     71\u001b[0m     \u001b[39m'\u001b[39m\u001b[39minput_size\u001b[39m\u001b[39m'\u001b[39m: [\u001b[39m21\u001b[39m],\n\u001b[0;32m     72\u001b[0m     \u001b[39m'\u001b[39m\u001b[39mhidden_size\u001b[39m\u001b[39m'\u001b[39m: [\u001b[39m21\u001b[39m],\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     78\u001b[0m     \u001b[39m'\u001b[39m\u001b[39mwashout\u001b[39m\u001b[39m'\u001b[39m: [\u001b[39m0\u001b[39m]\n\u001b[0;32m     79\u001b[0m }\n\u001b[0;32m     83\u001b[0m model \u001b[39m=\u001b[39m MyESN(input_size\u001b[39m=\u001b[39m\u001b[39m21\u001b[39m, initializer\u001b[39m=\u001b[39mw)\n\u001b[1;32m---> 85\u001b[0m run_experiment(\n\u001b[0;32m     86\u001b[0m     estimator\u001b[39m=\u001b[39;49mmodel,\n\u001b[0;32m     87\u001b[0m     data\u001b[39m=\u001b[39;49mdata,\n\u001b[0;32m     88\u001b[0m     param_dist\u001b[39m=\u001b[39;49mgrid,\n\u001b[0;32m     89\u001b[0m     input_columns\u001b[39m=\u001b[39;49m[\u001b[39m'\u001b[39;49m\u001b[39mbeta\u001b[39;49m\u001b[39m'\u001b[39;49m],\n\u001b[0;32m     90\u001b[0m     lag_size\u001b[39m=\u001b[39;49m\u001b[39m21\u001b[39;49m,\n\u001b[0;32m     91\u001b[0m     split_size\u001b[39m=\u001b[39;49m\u001b[39m5\u001b[39;49m,\n\u001b[0;32m     92\u001b[0m     opt_samples\u001b[39m=\u001b[39;49m\u001b[39m1\u001b[39;49m,\n\u001b[0;32m     93\u001b[0m     \u001b[39m# scoring=r2_score\u001b[39;49;00m\n\u001b[0;32m     94\u001b[0m )\n",
      "File \u001b[1;32mc:\\Users\\piotr\\Workspaces\\estimating-beta\\experiment.py:147\u001b[0m, in \u001b[0;36mrun_experiment\u001b[1;34m(estimator, data, param_dist, input_columns, lag_size, opt_samples, split_size, cv_outer_splits, cv_inner_splits, beta_corr_window, scoring, greater_is_better)\u001b[0m\n\u001b[0;32m    144\u001b[0m X \u001b[39m=\u001b[39m X\u001b[39m.\u001b[39mdropna()\n\u001b[0;32m    145\u001b[0m X, y \u001b[39m=\u001b[39m X\u001b[39m.\u001b[39mdrop(columns\u001b[39m=\u001b[39m\u001b[39m'\u001b[39m\u001b[39my\u001b[39m\u001b[39m'\u001b[39m), X[\u001b[39m'\u001b[39m\u001b[39my\u001b[39m\u001b[39m'\u001b[39m]\n\u001b[1;32m--> 147\u001b[0m \u001b[39mreturn\u001b[39;00m _run_experiment(estimator, X, y, param_dist, opt_samples, split_size, cv_outer_splits, cv_inner_splits, scoring, greater_is_better)\n",
      "File \u001b[1;32mc:\\Users\\piotr\\Workspaces\\estimating-beta\\experiment.py:179\u001b[0m, in \u001b[0;36m_run_experiment\u001b[1;34m(estimator, X, y, param_dist, opt_samples, split_size, cv_outer_splits, cv_inner_splits, scoring, greater_is_better)\u001b[0m\n\u001b[0;32m    176\u001b[0m \u001b[39m# print(f'Running fold {X_train.index.min()} - {X_test.index.max()}')\u001b[39;00m\n\u001b[0;32m    177\u001b[0m start \u001b[39m=\u001b[39m time()\n\u001b[1;32m--> 179\u001b[0m best_model \u001b[39m=\u001b[39m optimize_model(\n\u001b[0;32m    180\u001b[0m     estimator,\n\u001b[0;32m    181\u001b[0m     X_train, y_train,\n\u001b[0;32m    182\u001b[0m     param_dist,\n\u001b[0;32m    183\u001b[0m     opt_samples,\n\u001b[0;32m    184\u001b[0m     cv_inner_splits,\n\u001b[0;32m    185\u001b[0m     split_size,\n\u001b[0;32m    186\u001b[0m     scoring,\n\u001b[0;32m    187\u001b[0m     greater_is_better\n\u001b[0;32m    188\u001b[0m )\n\u001b[0;32m    190\u001b[0m y_pred \u001b[39m=\u001b[39m best_model\u001b[39m.\u001b[39mpredict(X_test)\n\u001b[0;32m    191\u001b[0m scores\u001b[39m.\u001b[39mappend(scoring(y_test, y_pred))\n",
      "File \u001b[1;32mc:\\Users\\piotr\\Workspaces\\estimating-beta\\experiment.py:62\u001b[0m, in \u001b[0;36moptimize_model\u001b[1;34m(estimator, X, y, params_dist, opt_samples, train_splits, split_size, scoring, greater_is_better)\u001b[0m\n\u001b[0;32m     51\u001b[0m train_size \u001b[39m=\u001b[39m train_splits \u001b[39m*\u001b[39m split_size\n\u001b[0;32m     53\u001b[0m folds \u001b[39m=\u001b[39m TimeSeriesSplit(max_train_size\u001b[39m=\u001b[39mtrain_size, n_splits\u001b[39m=\u001b[39mn_splits)\n\u001b[0;32m     55\u001b[0m \u001b[39mreturn\u001b[39;00m RandomizedSearchCV(\n\u001b[0;32m     56\u001b[0m     estimator,\n\u001b[0;32m     57\u001b[0m     param_distributions\u001b[39m=\u001b[39;49mparams_dist,\n\u001b[0;32m     58\u001b[0m     n_iter\u001b[39m=\u001b[39;49mopt_samples,\n\u001b[0;32m     59\u001b[0m     refit\u001b[39m=\u001b[39;49m\u001b[39mTrue\u001b[39;49;00m,\n\u001b[0;32m     60\u001b[0m     cv\u001b[39m=\u001b[39;49mfolds\u001b[39m.\u001b[39;49msplit(X),\n\u001b[0;32m     61\u001b[0m     scoring\u001b[39m=\u001b[39;49mmake_scorer(scoring, greater_is_better\u001b[39m=\u001b[39;49mgreater_is_better)\n\u001b[1;32m---> 62\u001b[0m )\u001b[39m.\u001b[39;49mfit(X, y)\u001b[39m.\u001b[39mbest_estimator_\n",
      "File \u001b[1;32mc:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_search.py:874\u001b[0m, in \u001b[0;36mBaseSearchCV.fit\u001b[1;34m(self, X, y, groups, **fit_params)\u001b[0m\n\u001b[0;32m    868\u001b[0m     results \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_format_results(\n\u001b[0;32m    869\u001b[0m         all_candidate_params, n_splits, all_out, all_more_results\n\u001b[0;32m    870\u001b[0m     )\n\u001b[0;32m    872\u001b[0m     \u001b[39mreturn\u001b[39;00m results\n\u001b[1;32m--> 874\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_run_search(evaluate_candidates)\n\u001b[0;32m    876\u001b[0m \u001b[39m# multimetric is determined here because in the case of a callable\u001b[39;00m\n\u001b[0;32m    877\u001b[0m \u001b[39m# self.scoring the return type is only known after calling\u001b[39;00m\n\u001b[0;32m    878\u001b[0m first_test_score \u001b[39m=\u001b[39m all_out[\u001b[39m0\u001b[39m][\u001b[39m\"\u001b[39m\u001b[39mtest_scores\u001b[39m\u001b[39m\"\u001b[39m]\n",
      "File \u001b[1;32mc:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_search.py:1768\u001b[0m, in \u001b[0;36mRandomizedSearchCV._run_search\u001b[1;34m(self, evaluate_candidates)\u001b[0m\n\u001b[0;32m   1766\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_run_search\u001b[39m(\u001b[39mself\u001b[39m, evaluate_candidates):\n\u001b[0;32m   1767\u001b[0m \u001b[39m    \u001b[39m\u001b[39m\"\"\"Search n_iter candidates from param_distributions\"\"\"\u001b[39;00m\n\u001b[1;32m-> 1768\u001b[0m     evaluate_candidates(\n\u001b[0;32m   1769\u001b[0m         ParameterSampler(\n\u001b[0;32m   1770\u001b[0m             \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mparam_distributions, \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mn_iter, random_state\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mrandom_state\n\u001b[0;32m   1771\u001b[0m         )\n\u001b[0;32m   1772\u001b[0m     )\n",
      "File \u001b[1;32mc:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_search.py:851\u001b[0m, in \u001b[0;36mBaseSearchCV.fit.<locals>.evaluate_candidates\u001b[1;34m(candidate_params, cv, more_results)\u001b[0m\n\u001b[0;32m    844\u001b[0m \u001b[39melif\u001b[39;00m \u001b[39mlen\u001b[39m(out) \u001b[39m!=\u001b[39m n_candidates \u001b[39m*\u001b[39m n_splits:\n\u001b[0;32m    845\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mValueError\u001b[39;00m(\n\u001b[0;32m    846\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mcv.split and cv.get_n_splits returned \u001b[39m\u001b[39m\"\u001b[39m\n\u001b[0;32m    847\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39minconsistent results. Expected \u001b[39m\u001b[39m{}\u001b[39;00m\u001b[39m \u001b[39m\u001b[39m\"\u001b[39m\n\u001b[0;32m    848\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39msplits, got \u001b[39m\u001b[39m{}\u001b[39;00m\u001b[39m\"\u001b[39m\u001b[39m.\u001b[39mformat(n_splits, \u001b[39mlen\u001b[39m(out) \u001b[39m/\u001b[39m\u001b[39m/\u001b[39m n_candidates)\n\u001b[0;32m    849\u001b[0m     )\n\u001b[1;32m--> 851\u001b[0m _warn_or_raise_about_fit_failures(out, \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49merror_score)\n\u001b[0;32m    853\u001b[0m \u001b[39m# For callable self.scoring, the return type is only know after\u001b[39;00m\n\u001b[0;32m    854\u001b[0m \u001b[39m# calling. If the return type is a dictionary, the error scores\u001b[39;00m\n\u001b[0;32m    855\u001b[0m \u001b[39m# can now be inserted with the correct key. The type checking\u001b[39;00m\n\u001b[0;32m    856\u001b[0m \u001b[39m# of out will be done in `_insert_error_scores`.\u001b[39;00m\n\u001b[0;32m    857\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mcallable\u001b[39m(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mscoring):\n",
      "File \u001b[1;32mc:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:367\u001b[0m, in \u001b[0;36m_warn_or_raise_about_fit_failures\u001b[1;34m(results, error_score)\u001b[0m\n\u001b[0;32m    360\u001b[0m \u001b[39mif\u001b[39;00m num_failed_fits \u001b[39m==\u001b[39m num_fits:\n\u001b[0;32m    361\u001b[0m     all_fits_failed_message \u001b[39m=\u001b[39m (\n\u001b[0;32m    362\u001b[0m         \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39mAll the \u001b[39m\u001b[39m{\u001b[39;00mnum_fits\u001b[39m}\u001b[39;00m\u001b[39m fits failed.\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[0;32m    363\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mIt is very likely that your model is misconfigured.\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[0;32m    364\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mYou can try to debug the error by setting error_score=\u001b[39m\u001b[39m'\u001b[39m\u001b[39mraise\u001b[39m\u001b[39m'\u001b[39m\u001b[39m.\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m\\n\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[0;32m    365\u001b[0m         \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mBelow are more details about the failures:\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m{\u001b[39;00mfit_errors_summary\u001b[39m}\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[0;32m    366\u001b[0m     )\n\u001b[1;32m--> 367\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mValueError\u001b[39;00m(all_fits_failed_message)\n\u001b[0;32m    369\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m    370\u001b[0m     some_fits_failed_message \u001b[39m=\u001b[39m (\n\u001b[0;32m    371\u001b[0m         \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m{\u001b[39;00mnum_failed_fits\u001b[39m}\u001b[39;00m\u001b[39m fits failed out of a total of \u001b[39m\u001b[39m{\u001b[39;00mnum_fits\u001b[39m}\u001b[39;00m\u001b[39m.\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[0;32m    372\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mThe score on these train-test partitions for these parameters\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    376\u001b[0m         \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mBelow are more details about the failures:\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m{\u001b[39;00mfit_errors_summary\u001b[39m}\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[0;32m    377\u001b[0m     )\n",
      "\u001b[1;31mValueError\u001b[0m: \nAll the 59 fits failed.\nIt is very likely that your model is misconfigured.\nYou can try to debug the error by setting error_score='raise'.\n\nBelow are more details about the failures:\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\piotr\\AppData\\Local\\Temp\\ipykernel_7892\\2658662950.py\", line 33, in fit\n    return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\esn.py\", line 21, in fit\n    self.readout.fit(mapped_input, target, washout=self.washout)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\readout\\nn_readout.py\", line 60, in fit\n    y_pred = self.model(X)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 217, in forward\n    input = module(input)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    return F.linear(input, self.weight, self.bias)\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (5x42 and 21x4)\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\piotr\\AppData\\Local\\Temp\\ipykernel_7892\\2658662950.py\", line 33, in fit\n    return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\esn.py\", line 21, in fit\n    self.readout.fit(mapped_input, target, washout=self.washout)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\readout\\nn_readout.py\", line 60, in fit\n    y_pred = self.model(X)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 217, in forward\n    input = module(input)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    return F.linear(input, self.weight, self.bias)\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (10x42 and 21x4)\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\piotr\\AppData\\Local\\Temp\\ipykernel_7892\\2658662950.py\", line 33, in fit\n    return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\esn.py\", line 21, in fit\n    self.readout.fit(mapped_input, target, washout=self.washout)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\readout\\nn_readout.py\", line 60, in fit\n    y_pred = self.model(X)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 217, in forward\n    input = module(input)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    return F.linear(input, self.weight, self.bias)\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (15x42 and 21x4)\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\piotr\\AppData\\Local\\Temp\\ipykernel_7892\\2658662950.py\", line 33, in fit\n    return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\esn.py\", line 21, in fit\n    self.readout.fit(mapped_input, target, washout=self.washout)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\readout\\nn_readout.py\", line 60, in fit\n    y_pred = self.model(X)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 217, in forward\n    input = module(input)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    return F.linear(input, self.weight, self.bias)\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (20x42 and 21x4)\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\piotr\\AppData\\Local\\Temp\\ipykernel_7892\\2658662950.py\", line 33, in fit\n    return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\esn.py\", line 21, in fit\n    self.readout.fit(mapped_input, target, washout=self.washout)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\readout\\nn_readout.py\", line 60, in fit\n    y_pred = self.model(X)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 217, in forward\n    input = module(input)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    return F.linear(input, self.weight, self.bias)\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (25x42 and 21x4)\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\piotr\\AppData\\Local\\Temp\\ipykernel_7892\\2658662950.py\", line 33, in fit\n    return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\esn.py\", line 21, in fit\n    self.readout.fit(mapped_input, target, washout=self.washout)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\readout\\nn_readout.py\", line 60, in fit\n    y_pred = self.model(X)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 217, in forward\n    input = module(input)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    return F.linear(input, self.weight, self.bias)\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (30x42 and 21x4)\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\piotr\\AppData\\Local\\Temp\\ipykernel_7892\\2658662950.py\", line 33, in fit\n    return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\esn.py\", line 21, in fit\n    self.readout.fit(mapped_input, target, washout=self.washout)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\readout\\nn_readout.py\", line 60, in fit\n    y_pred = self.model(X)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 217, in forward\n    input = module(input)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    return F.linear(input, self.weight, self.bias)\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (35x42 and 21x4)\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\piotr\\AppData\\Local\\Temp\\ipykernel_7892\\2658662950.py\", line 33, in fit\n    return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\esn.py\", line 21, in fit\n    self.readout.fit(mapped_input, target, washout=self.washout)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\readout\\nn_readout.py\", line 60, in fit\n    y_pred = self.model(X)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 217, in forward\n    input = module(input)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    return F.linear(input, self.weight, self.bias)\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (40x42 and 21x4)\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\piotr\\AppData\\Local\\Temp\\ipykernel_7892\\2658662950.py\", line 33, in fit\n    return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\esn.py\", line 21, in fit\n    self.readout.fit(mapped_input, target, washout=self.washout)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\readout\\nn_readout.py\", line 60, in fit\n    y_pred = self.model(X)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 217, in forward\n    input = module(input)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    return F.linear(input, self.weight, self.bias)\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (45x42 and 21x4)\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\piotr\\AppData\\Local\\Temp\\ipykernel_7892\\2658662950.py\", line 33, in fit\n    return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\esn.py\", line 21, in fit\n    self.readout.fit(mapped_input, target, washout=self.washout)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\readout\\nn_readout.py\", line 60, in fit\n    y_pred = self.model(X)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 217, in forward\n    input = module(input)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    return F.linear(input, self.weight, self.bias)\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (50x42 and 21x4)\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\piotr\\AppData\\Local\\Temp\\ipykernel_7892\\2658662950.py\", line 33, in fit\n    return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\esn.py\", line 21, in fit\n    self.readout.fit(mapped_input, target, washout=self.washout)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\readout\\nn_readout.py\", line 60, in fit\n    y_pred = self.model(X)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 217, in forward\n    input = module(input)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    return F.linear(input, self.weight, self.bias)\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (55x42 and 21x4)\n\n--------------------------------------------------------------------------------\n48 fits failed with the following error:\nTraceback (most recent call last):\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\piotr\\AppData\\Local\\Temp\\ipykernel_7892\\2658662950.py\", line 33, in fit\n    return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\esn.py\", line 21, in fit\n    self.readout.fit(mapped_input, target, washout=self.washout)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\auto_esn\\esn\\readout\\nn_readout.py\", line 60, in fit\n    y_pred = self.model(X)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\container.py\", line 217, in forward\n    input = module(input)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\module.py\", line 1501, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"c:\\Users\\piotr\\Workspaces\\estimating-beta\\.venv\\lib\\site-packages\\torch\\nn\\modules\\linear.py\", line 114, in forward\n    return F.linear(input, self.weight, self.bias)\nRuntimeError: mat1 and mat2 shapes cannot be multiplied (60x42 and 21x4)\n"
     ]
    }
   ],
   "source": [
    "from auto_esn.esn.esn import FlexDeepESN\n",
    "from auto_esn.esn.reservoir import activation as A\n",
    "from auto_esn.esn.reservoir.initialization import CompositeInitializer, WeightInitializer\n",
    "from auto_esn.esn.readout.nn_readout import AutoNNReadout\n",
    "import torch\n",
    "from sklearn.metrics import r2_score\n",
    "import numpy as np \n",
    "import pandas as pd\n",
    "\n",
    "\n",
    "device = torch.device('cpu')\n",
    "dtype = torch.double\n",
    "torch.set_default_dtype(dtype)\n",
    "readout = A\n",
    "class MyESN(FlexDeepESN):\n",
    "    def __init__(self, readout = AutoNNReadout, input_size: int = 1, hidden_size: int = 500, output_dim: int = 1, bias: bool = False, initializer: WeightInitializer = WeightInitializer(), num_layers=2, activation=A.self_normalizing_default(), washout: int = 30):\n",
    "        rd = readout(input_size*num_layers)\n",
    "        super().__init__(rd, input_size, hidden_size, bias, initializer, num_layers, activation, washout)\n",
    "        self.rd_class = readout\n",
    "        self.input_size = input_size\n",
    "        self.hidden_size = hidden_size\n",
    "        self.output_dim = output_dim\n",
    "        self.bias = bias\n",
    "        self.initializer = initializer\n",
    "        self.num_layers= num_layers\n",
    "        self.activation = activation\n",
    "        self.washout = washout\n",
    "\n",
    "    def fit(self, X, y): \n",
    "        if  isinstance(X, pd.DataFrame):\n",
    "            X = X.to_numpy()\n",
    "            y = y.to_numpy()\n",
    "        return super().fit(torch.from_numpy(X), torch.from_numpy(y))\n",
    "\n",
    "    def predict(self, X):\n",
    "        if  isinstance(X, pd.DataFrame):\n",
    "            X = X.to_numpy()\n",
    "\n",
    "        mapped_input = self.reservoir(torch.from_numpy(X))\n",
    "        return self.readout(mapped_input)[:,-X.shape[0]]\n",
    "        # return np.squeeze(self(torch.tensor(X, device=device)))\n",
    "    \n",
    "    def get_params(self, deep=False):\n",
    "        return {\"readout\": self.rd_class, \"input_size\": self.input_size, \"hidden_size\": self.hidden_size,\"output_dim\": self.output_dim, \"bias\": self.bias,\"initializer\": self.initializer, \"num_layers\": self.num_layers,\"activation\": self.activation, \"washout\": self.washout}\n",
    "    def set_params(self, **params):\n",
    "        return MyESN(**params)\n",
    "\n",
    "from experiment import run_experiment, build_data\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "data = build_data(\n",
    "    stock='GOOG',\n",
    "    market='^spx',\n",
    "    risk_free='risk_free_us.csv'\n",
    ").fillna(0)\n",
    "\n",
    "i = CompositeInitializer()\\\n",
    "    .with_seed(23)\\\n",
    "    # .sparse(density=1)\\\n",
    "    # .spectral_noisy(spectral_radius=1.5, noise_magnitude=0.1)\\\n",
    "    # .uniform()\\\n",
    "    # .regular_graph(4)\\\n",
    "    # .scale(0.9)\\\n",
    "    \n",
    "w = WeightInitializer()\n",
    "w.weight_hh_init = i\n",
    "\n",
    "grid = {\n",
    "    'input_size': [21],\n",
    "    'hidden_size': [21],\n",
    "    'output_dim': [1],\n",
    "    'bias': [False],\n",
    "    'initializer': [w],\n",
    "    'num_layers': [2],\n",
    "    'activation': [A.self_normalizing_default()],\n",
    "    'washout': [0]\n",
    "}\n",
    "\n",
    "\n",
    "\n",
    "model = MyESN(input_size=21, initializer=w)\n",
    "\n",
    "run_experiment(\n",
    "    estimator=model,\n",
    "    data=data,\n",
    "    param_dist=grid,\n",
    "    input_columns=['beta'],\n",
    "    lag_size=21,\n",
    "    split_size=5,\n",
    "    opt_samples=1,\n",
    "    # scoring=r2_score\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.11"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
